<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="2" total="8" passed="6">
  <reporter-output>
  </reporter-output>
  <suite name="Default suite" duration-ms="322" started-at="2019-10-03T15:01:30Z" finished-at="2019-10-03T15:01:31Z">
    <groups>
    </groups>
    <test name="Default test" duration-ms="322" started-at="2019-10-03T15:01:30Z" finished-at="2019-10-03T15:01:31Z">
      <class name="unittesting.mock.MockitoExampleTest">
        <test-method status="PASS" signature="testCallMethodThatIsNotMocked()[pri:0, instance:unittesting.mock.MockitoExampleTest@573f2bb1]" name="testCallMethodThatIsNotMocked" duration-ms="253" started-at="2019-10-03T17:01:30Z" finished-at="2019-10-03T17:01:31Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testCallMethodThatIsNotMocked -->
        <test-method status="PASS" signature="testForIOException()[pri:0, instance:unittesting.mock.MockitoExampleTest@573f2bb1]" name="testForIOException" duration-ms="2" started-at="2019-10-03T17:01:31Z" finished-at="2019-10-03T17:01:31Z">
          <exception class="java.io.IOException">
            <full-stacktrace>
              <![CDATA[java.io.IOException
	at unittesting.mock.MockitoExampleTest.testForIOException(MockitoExampleTest.java:53)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:86)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:643)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:820)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1128)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:782)
	at org.testng.TestRunner.run(TestRunner.java:632)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:366)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:361)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:319)
	at org.testng.SuiteRunner.run(SuiteRunner.java:268)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1244)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1169)
	at org.testng.TestNG.run(TestNG.java:1064)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.io.IOException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testForIOException -->
        <test-method status="FAIL" signature="testMoreThanOneReturnValue()[pri:0, instance:unittesting.mock.MockitoExampleTest@573f2bb1]" name="testMoreThanOneReturnValue" duration-ms="29" started-at="2019-10-03T17:01:31Z" finished-at="2019-10-03T17:01:31Z">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [Hello bug-seeders!] but found [Hello testers!]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [Hello bug-seeders!] but found [Hello testers!]
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.failNotEquals(Assert.java:513)
	at org.testng.Assert.assertEqualsImpl(Assert.java:135)
	at org.testng.Assert.assertEquals(Assert.java:116)
	at org.testng.Assert.assertEquals(Assert.java:190)
	at org.testng.Assert.assertEquals(Assert.java:200)
	at unittesting.mock.MockitoExampleTest.testMoreThanOneReturnValue(MockitoExampleTest.java:67)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:86)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:643)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:820)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1128)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:782)
	at org.testng.TestRunner.run(TestRunner.java:632)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:366)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:361)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:319)
	at org.testng.SuiteRunner.run(SuiteRunner.java:268)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1244)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1169)
	at org.testng.TestNG.run(TestNG.java:1064)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testMoreThanOneReturnValue -->
        <test-method status="PASS" signature="testReturnValueDependentOnMethodParameter()[pri:0, instance:unittesting.mock.MockitoExampleTest@573f2bb1]" name="testReturnValueDependentOnMethodParameter" duration-ms="15" started-at="2019-10-03T17:01:31Z" finished-at="2019-10-03T17:01:31Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testReturnValueDependentOnMethodParameter -->
        <test-method status="PASS" signature="testReturnValueInDependentOnMethodParameter()[pri:0, instance:unittesting.mock.MockitoExampleTest@573f2bb1]" name="testReturnValueInDependentOnMethodParameter" duration-ms="1" started-at="2019-10-03T17:01:31Z" finished-at="2019-10-03T17:01:31Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testReturnValueInDependentOnMethodParameter -->
        <test-method status="PASS" signature="testSimpleReturnValue()[pri:0, instance:unittesting.mock.MockitoExampleTest@573f2bb1]" name="testSimpleReturnValue" duration-ms="1" started-at="2019-10-03T17:01:31Z" finished-at="2019-10-03T17:01:31Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testSimpleReturnValue -->
        <test-method status="PASS" signature="testSimpleReturnValue2()[pri:0, instance:unittesting.mock.MockitoExampleTest@573f2bb1]" name="testSimpleReturnValue2" duration-ms="1" started-at="2019-10-03T17:01:31Z" finished-at="2019-10-03T17:01:31Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testSimpleReturnValue2 -->
        <test-method status="FAIL" signature="testStringMockEquals()[pri:0, instance:unittesting.mock.MockitoExampleTest@573f2bb1]" name="testStringMockEquals" duration-ms="1" started-at="2019-10-03T17:01:31Z" finished-at="2019-10-03T17:01:31Z">
          <exception class="org.mockito.exceptions.base.MockitoException">
            <message>
              <![CDATA[
Cannot mock/spy class java.lang.String
Mockito cannot mock/spy because :
 - final or anonymous class]]>
            </message>
            <full-stacktrace>
              <![CDATA[org.mockito.exceptions.base.MockitoException: 
Cannot mock/spy class java.lang.String
Mockito cannot mock/spy because :
 - final or anonymous class
	at unittesting.mock.MockitoExampleTest.testStringMockEquals(MockitoExampleTest.java:108)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:86)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:643)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:820)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1128)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:782)
	at org.testng.TestRunner.run(TestRunner.java:632)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:366)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:361)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:319)
	at org.testng.SuiteRunner.run(SuiteRunner.java:268)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1244)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1169)
	at org.testng.TestNG.run(TestNG.java:1064)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- org.mockito.exceptions.base.MockitoException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testStringMockEquals -->
      </class> <!-- unittesting.mock.MockitoExampleTest -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
